/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Singleton.Conexion;
import javax.swing.JOptionPane;

/**
 *
 * @author PC-4
 */
public class vista_registrar_empleado extends javax.swing.JFrame {

    /**
     * Creates new form vista_registrar_empleado
     */
    public vista_registrar_empleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nombre = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Apellido = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 100));
        setMinimumSize(new java.awt.Dimension(900, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        Nombre.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        Nombre.setText("Nombres:");
        getContentPane().add(Nombre);
        Nombre.setBounds(30, 120, 110, 50);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Registrar Empleado");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(290, 40, 370, 50);

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel2.setText("Estado Civil:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(440, 230, 130, 27);

        Apellido.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        Apellido.setText("Apellidos:");
        getContentPane().add(Apellido);
        Apellido.setBounds(30, 170, 110, 50);

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel4.setText("Cedula:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 220, 80, 50);

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel5.setText("Email:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 330, 55, 27);

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel6.setText("Dir. Domicilio:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(440, 180, 150, 30);

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel7.setText("Telf. Trabajo:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(440, 130, 140, 27);

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel8.setText("Celular:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 260, 130, 70);

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel9.setText("Cargo:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(440, 280, 66, 27);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(150, 130, 270, 30);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(150, 180, 270, 30);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(150, 230, 270, 30);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(150, 330, 270, 30);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(150, 280, 270, 30);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(590, 130, 280, 30);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(590, 180, 280, 30);
        getContentPane().add(jTextField8);
        jTextField8.setBounds(590, 230, 280, 30);
        getContentPane().add(jTextField9);
        jTextField9.setBounds(590, 280, 280, 30);

        jButton1.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jButton1.setText("Registrar");
        getContentPane().add(jButton1);
        jButton1.setBounds(670, 450, 130, 40);

        btnAtras.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtras);
        btnAtras.setBounds(100, 450, 130, 40);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/registro_1.jpg"))); // NOI18N
        getContentPane().add(fondo);
        fondo.setBounds(-20, -60, 930, 660);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        String nombre = jTextField1.getText();
        String apellido = jTextField2.getText();
        String cedula =  jTextField3.getText();
        String correo = jTextField4.getText();
        String celular = jTextField5.getText();
        String TelfTra = jTextField6.getText();
        String Direccion = jTextField7.getText();
        String EstadoCivil = jTextField8.getText();
        String Cargo = jTextField9.getText();
        /*String user = jTextField.getText();
        String password = new String(jPasswordField1.getPassword());
        if (nombre.length() > 0 && apellido.length() > 0 && cedula.length() > 0 && celular.length() > 0 && Direccion.length() > 0 && correo.length() > 0 && Cargo.length() > 0 
        && TelfTra.length() > 0 && EstadoCivil.length() > 0 &&user.length() > 0 && password.length() > 0 ){
            if(RegistrarEmpleado(IdEmpleado,Contraseña,Nombre,Apellido,Cedula,Celular,Correo,Direccion,telTrabajo,EstadoCivil,Cargo)){
                JOptionPane.showMessageDialog(null, "Registro Exitoso");
                vista_login vlog= new vista_login();
                vlog.setVisible(true);
                dispose();
            }else{
                JOptionPane.showMessageDialog(null, "El Usuario ya se encuentra registrado");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Los Campos son Obligatorios");
        } */
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        vista_admin a = new vista_admin();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vista_registrar_empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vista_registrar_empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vista_registrar_empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vista_registrar_empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vista_registrar_empleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apellido;
    private javax.swing.JLabel Nombre;
    private javax.swing.JButton btnAtras;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables

    public boolean RegistrarEmpleado(String user, String password,String nombre,String apellido,String cedula,String Celular, String correo, String Direccion, String TelfTra, String EstadoCivil, String Cargo){
        Conexion conexion = Conexion.getInstancia();
        try{
            String SQL1 = "SELECT * FROM Empleados WHERE IdCliente = '"+user+"'";
            String SQL2 = "INSERT Empleados(IdEmpleado,Contraseña,Nombre,Apellido,Cedula,Celular,Correo,Direccion,telTrabajo,EstadoCivil,Cargo) VALUES ('"+user+"','"+password+"','"+nombre+"','"+apellido+"','"+cedula+"','"+Celular+"','"+correo+"','"+Direccion+"','"+TelfTra+"','"+EstadoCivil+"','"+Cargo+"')";
            if(conexion.Actualizar(SQL1, SQL2)){
                return true;
            }else{return false;}
        }catch (Exception e) {
            e.printStackTrace();
        }
        return false;
    }

}
