/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Singleton.Conexion;

/**
 *
 * @author PC-4
 */
public class vista_crearCasaPredisenada extends javax.swing.JFrame {

    /**
     * Creates new form vista_crearCasaPredisenada
     */
    public vista_crearCasaPredisenada() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtM2 = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtNpisos = new javax.swing.JTextField();
        txtNbanios = new javax.swing.JTextField();
        txtNHabitaciones = new javax.swing.JTextField();
        txtOrientacion = new javax.swing.JTextField();
        txtPatio = new javax.swing.JTextField();
        txtEsquinera = new javax.swing.JTextField();
        btnAtras = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 100));
        setMinimumSize(new java.awt.Dimension(900, 600));
        getContentPane().setLayout(null);

        lbTitulo.setFont(new java.awt.Font("Tw Cen MT", 2, 48)); // NOI18N
        lbTitulo.setText("Casa Prediseñada");
        getContentPane().add(lbTitulo);
        lbTitulo.setBounds(300, 20, 400, 70);

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel2.setText("Nombre: ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 110, 110, 30);

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel3.setText("Metros Cuadrados :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 170, 150, 20);

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel4.setText("Numero de pisos:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 210, 140, 30);

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel5.setText("Numero de habitaciones :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 320, 190, 21);

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel6.setText("Patio:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(80, 420, 80, 21);

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel7.setText("Orientación:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(80, 370, 110, 21);

        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(840, 330, 41, 16);

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel9.setText("Numero de baños:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(80, 270, 140, 20);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel1.setText("Es esquinera:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 470, 110, 21);
        getContentPane().add(txtM2);
        txtM2.setBounds(270, 160, 290, 30);
        getContentPane().add(txtNombre);
        txtNombre.setBounds(270, 110, 290, 30);
        getContentPane().add(txtNpisos);
        txtNpisos.setBounds(270, 210, 290, 30);
        getContentPane().add(txtNbanios);
        txtNbanios.setBounds(270, 260, 290, 30);
        getContentPane().add(txtNHabitaciones);
        txtNHabitaciones.setBounds(270, 310, 290, 30);
        getContentPane().add(txtOrientacion);
        txtOrientacion.setBounds(270, 360, 290, 30);
        getContentPane().add(txtPatio);
        txtPatio.setBounds(270, 410, 290, 30);
        getContentPane().add(txtEsquinera);
        txtEsquinera.setBounds(270, 460, 290, 30);

        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtras);
        btnAtras.setBounds(50, 510, 63, 30);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/registro_1.jpg"))); // NOI18N
        fondo.setMaximumSize(new java.awt.Dimension(900, 600));
        fondo.setMinimumSize(new java.awt.Dimension(900, 600));
        fondo.setPreferredSize(new java.awt.Dimension(900, 600));
        getContentPane().add(fondo);
        fondo.setBounds(-60, -430, 1980, 1230);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        vista_admin a= new vista_admin();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vista_crearCasaPredisenada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vista_crearCasaPredisenada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vista_crearCasaPredisenada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vista_crearCasaPredisenada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vista_crearCasaPredisenada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JTextField txtEsquinera;
    private javax.swing.JTextField txtM2;
    private javax.swing.JTextField txtNHabitaciones;
    private javax.swing.JTextField txtNbanios;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNpisos;
    private javax.swing.JTextField txtOrientacion;
    private javax.swing.JTextField txtPatio;
    // End of variables declaration//GEN-END:variables

    public boolean AgregarCasaPre(String Nombre, String Metros2, String nPisos, String Esquinera, String Orientacion, String TPatio, String nHabitaciones, String nBaños){
        Conexion conexion = Conexion.getInstancia();
        try{
            String SQL1 = "SELECT * FROM CasasPre WHERE Nombre = '"+Nombre+"'";
            String SQL2 = "INSERT CasasPre(Nombre,Metros2,nPisos,Esquinera,Orientacion,TPatio,nHabitaciones,nBaños) VALUES ('"+Nombre+"','"+Metros2+"','"+nPisos+"','"+Esquinera+"','"+Orientacion+"','"+TPatio+"','"+nHabitaciones+"','"+nBaños+"')";
            if(conexion.Actualizar(SQL1, SQL2)){
                return true;
            }else{return false;}
        }catch (Exception e) {
            e.printStackTrace();
        }
        return false;
        
        /*
        String Nombre = txtNombre.getText();
        String Metros2 = txtM2.getText();
        String nPisos =  txtNpisos.getText();
        String Esquinera = txtEsquinera.getText();
        String Orientacion = txtOrientacion.getText();
        String TPatio = txtPatio.getText();
        String nHabitaciones = txtNHabitaciones.getText();
        String nBaños = txtNbanios.getText();
        if (Nombre.length() > 0 && Metros2.length() > 0 && nPisos.length() > 0 && Esquinera.length() > 0 && Orientacion.length() > 0 && TPatio.length() > 0 && nHabitaciones.length() > 0 && nBaños.length() > 0 ){
            if(AgregarCasaPre(Nombre,Metros2,nPisos,Esquinera,Orientacion,TPatio,nHabitaciones,nBaños)){
                JOptionPane.showMessageDialog(null, "Registro Exitoso");
                vista_login vlog= new vista_login();
                vlog.setVisible(true);
                dispose();
            }else{
                JOptionPane.showMessageDialog(null, "La Casa ya se encuentra registrada");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Los Campos son Obligatorios");
        } */
    }

}
